CREATE OR REPLACE DATABASE MANAGE_DB;
CREATE OR REPLACE SCHEMA external_stages;
USE DATABASE MANAGE_DB;
USE SCHEMA external_stages;

CREATE OR REPLACE STAGE MANAGE_DB.external_stages.aws_stage_errorex
  URL='s3://bucketsnowflakes4'

  LIST @MANAGE_DB.external_stages.aws_stage_errorex;

CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.ORDERS_EX (
   ORDER_ID VARCHAR(30),
   AMOUNT INT,
   PROFIT INT,
   QUANTITY INT,
   CATEGORY VARCHAR(30),
   SUBCATEGORY VARCHAR(30)
);

COPY INTO OUR_FIRST_DB.PUBLIC.ORDERS_EX
  FROM @MANAGE_DB.external_stages.aws_stage_errorex
  FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ',' SKIP_HEADER = 1)
  ON_ERROR = 'CONTINUE';


SELECT * FROM OUR_FIRST_DB.PUBLIC.ORDERS_EX;
