CREATE OR  REPLACE STAGE MANAGE_DB.EXTERNAL_STAGES.JSONSTAGE
URL='s3://bucketsnowflake-jsondemo'
FILE_FORMAT=(TYPE=JSON);

LIST @JSONSTAGE;

CREATE OR  REPLACE SCHEMA MANAGE_DB.FILE_FORMATS;



CREATE OR REPLACE FILE FORMAT FILE_FORMATS.JSONFORMAT
TYPE=JSON;


CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.JSON_RAW(
raw_file VARIANT
);


SELECT * FROM OUR_FIRST_DB.PUBLIC.JSON_RAW;


COPY INTO OUR_FIRST_DB.PUBLIC.JSON_RAW
FROM @MANAGE_DB.EXTERNAL_STAGES.JSONSTAGE
FILES=('HR_data.json')
FILE_FORMAT=(TYPE=JSON);



SELECT RAW_FILE:city
FROM OUR_FIRST_DB.PUBLIC.JSON_RAW;

SELECT $1:city
FROM OUR_FIRST_DB.PUBLIC.JSON_RAW;


SELECT RAW_FILE:first_name::STRING AS FIRST_NAME
FROM OUR_FIRST_DB.PUBLIC.JSON_RAW;


SELECT 
RAW_FILE:id::INT AS id,
RAW_FILE:first_name::STRING AS first_name,
RAW_FILE:gender::STRING AS gender
FROM OUR_FIRST_DB.PUBLIC.JSON_RAW;


SELECT RAW_FILE:job  AS job
FROM OUR_FIRST_DB.PUBLIC.JSON_RAW;



SELECT RAW_FILE:job.title  AS job_title
FROM OUR_FIRST_DB.PUBLIC.JSON_RAW;



SELECT RAW_FILE:spoken_languages  AS spoken_languages
FROM OUR_FIRST_DB.PUBLIC.JSON_RAW;


SELECT array_size(RAW_FILE:spoken_languages)  AS spoken_languages
FROM OUR_FIRST_DB.PUBLIC.JSON_RAW;


SELECT RAW_FILE:prev_company  AS prev_company
FROM OUR_FIRST_DB.PUBLIC.JSON_RAW;



SELECT RAW_FILE:prev_company[1]::STRING AS prev_company
FROM OUR_FIRST_DB.PUBLIC.JSON_RAW;


CREATE OR REPLACE TABLE Languages AS
select
      RAW_FILE:first_name::STRING as First_name,
    f.value:language::STRING as First_language,
   f.value:level::STRING as Level_spoken
from OUR_FIRST_DB.PUBLIC.JSON_RAW, table(flatten(RAW_FILE:spoken_languages)) f;



select * from languages;