show warehouses;
CREATE WAREHOUSE sales_wh with
WAREHOUSE_SIZE='SMALL'
AUTO_SUSPEND=180
AUTO_RESUME=TRUE
INITIALLY_SUSPENDED=TRUE;

ALTER WAREHOUSE SALES_WH
SET WAREHOUSE_SIZE='XSMALL'
AUTO_SUSPEND=120

ALTER WAREHOUSE SALES_WH RESUME;
ALTER WAREHOUSE SALES_WH SUSPEND;

USE WAREHOUSE SALES_WH;

SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_LOAD_HISTORY

SHOW WAREHOUSES LIKE 'SALES_WH'

CREATE WAREHOUSE ETL_WH
MIN_CLUSTER_COUNT=1
MAX_CLUSTER_COUNT=1
SCALING_POLICY='ECONOMY';

SHOW WAREHOUSES LIKE 'ETL_WH'
