CREATE OR REPLACE DATABASE TRAINING_DB;
CREATE OR REPLACE SCHEMA TRAINING_DB.RAW;
CREATE OR REPLACE TABLE TRAINING_DB.RAW.SALES(ID INT,CUSTOMER STRING,AMOUNT FLOAT,SALE_DATE DATE);
INSERT INTO SALES VALUES(1,'KAVYA',567,'2020-11-26');
SELECT * FROM SALES
