CREATE OR REPLACE DATABASE MANAGE_DB;
CREATE OR REPLACE SCHEMA MANAGE_DB.external_stages;
CREATE OR REPLACE STAGE MANAGE_DB.external_stages.aws_stage
url='s3://bucketsnowflakes3';

SHOW STAGES IN MANAGE_DB.EXTERNAL_STAGES;

CREATE OR REPLACE DATABASE OUR_FIRST_DB;

USE DATABASE OUR_FIRST_DB;
USE SCHEMA PUBLIC;

CREATE OR REPLACE TABLE ORDERS (
    ORDER_ID STRING,
    PRODUCT_PRICE INT,
    DISCOUNT INT,
    QUANTITY INT,
    PRODUCT_TYPE STRING,
    PRODUCT_NAME STRING
);


COPY INTO OUR_FIRST_DB.PUBLIC.ORDERS
FROM @MANAGE_DB.external_stages.aws_stage
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ',' SKIP_HEADER = 1)
PATTERN = '.*OrderDetails.*'

SELECT * FROM OUR_FIRST_DB.PUBLIC.ORDERS;

CREATE OR REPLACE TABLE ORDERS_CACHING (
ORDER_ID	VARCHAR(30)
,AMOUNT	NUMBER(38,0)
,PROFIT	NUMBER(38,0)
,QUANTITY	NUMBER(38,0)
,CATEGORY	VARCHAR(30)
,SUBCATEGORY	VARCHAR(30)
,DATE DATE)   ; 


DESC TABLE ORDERS;
 
INSERT INTO ORDERS_CACHING 
SELECT
  t1.ORDER_ID,
  t1.PRODUCT_PRICE        AS AMOUNT,         
  t1.DISCOUNT             AS PROFIT,       
  t1.QUANTITY,
  t1.PRODUCT_TYPE         AS CATEGORY,       
  t1.PRODUCT_NAME         AS SUBCATEGORY,    
  TO_DATE(TO_TIMESTAMP(UNIFORM(1500000000,1700000000,RANDOM()))) AS ORDER_DATE
FROM ORDERS t1
CROSS JOIN ORDERS t2;



SELECT * FROM ORDERS_CACHING  WHERE DATE = '2020-06-09';

