-- create dedicated warehouse for different purpose

 CREATE WAREHOUSE DS_WH
 WITH WAREHOUSE_SIZE='SMALL'
 WAREHOUSE_TYPE='STANDARD'
 AUTO_SUSPEND=300
 AUTO_RESUME=TRUE
 MIN_CLUSTER_COUNT=1
 MAX_CLUSTER_COUNT=1
 SCALING_POLICY='STANDARD';

 DROP WAREHOUSE DBA_WH;

 
 CREATE WAREHOUSE DBA_WH
 WITH WAREHOUSE_SIZE='XSMALL'
 WAREHOUSE_TYPE='STANDARD'
 AUTO_SUSPEND=300
 AUTO_RESUME=TRUE
 MIN_CLUSTER_COUNT=1
 MAX_CLUSTER_COUNT=1
 SCALING_POLICY='STANDARD';


 --CREATE ROLES AND GRANTING THE WAREHOUSE ACCESS

 CREATE ROLE DATA_SCIENTIST;
 GRANT USAGE ON WAREHOUSE DS_WH TO ROLE DATA_SCIENTIST;


CREATE ROLE DBA;
 GRANT USAGE ON WAREHOUSE DBA_WH TO ROLE DBA;

CREATE USER DS1 PASSWORD='DS1' LOGIN_NAME='DS1'
DEFAULT_ROLE='DATA_SCIENTIST' DEFAULT_WAREHOUSE='DS_WH' MUST_CHANGE_PASSWORD=FALSE;


CREATE USER DS2 PASSWORD='DS2' LOGIN_NAME='DS2'
DEFAULT_ROLE='DATA_SCIENTIST' DEFAULT_WAREHOUSE='DS_WH' MUST_CHANGE_PASSWORD=FALSE;

CREATE USER DS3 PASSWORD='DS3' LOGIN_NAME='DS3'
DEFAULT_ROLE='DATA_SCIENTIST' DEFAULT_WAREHOUSE='DS_WH' MUST_CHANGE_PASSWORD=FALSE;


GRANT ROLE DATA_SCIENTIST TO  USER DS1;
GRANT ROLE DATA_SCIENTIST TO USER DS2;
GRANT ROLE DATA_SCIENTIST TO USER DS3;


CREATE USER DBA1 PASSWORD='DBA1' LOGIN_NAME='DBA1'
DEFAULT_ROLE='DBA' DEFAULT_WAREHOUSE='DBA_WH' MUST_CHANGE_PASSWORD=FALSE;


CREATE USER DBA2 PASSWORD='DBA2' LOGIN_NAME='DBA2'
DEFAULT_ROLE='DBA' DEFAULT_WAREHOUSE='DBA_WH' MUST_CHANGE_PASSWORD=FALSE;

GRANT ROLE DBA TO USER DBA1;
GRANT ROLE DBA TO USER DBA2;

DROP USER DBA1;
DROP USER DBA2;

DROP USER DS1;
DROP USER DS2;
DROP USER DS3;


DROP ROLE DBA;
DROP ROLE DATA_SCIENTIST;

DROP WAREHOUSE DS_WH;
DROP WAREHOUSE DBA_WH;

SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.WEB_SITE T1
CROSS JOIN SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.WEB_SITE T2
CROSS JOIN SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.WEB_SITE T3
CROSS JOIN (SELECT TOP 57 * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.WEB_SITE)  T4;


select * from SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.call_center;

select * from snowflake_sample_data.tpcds_sf100tcl.customer;
SELECT AVG(C_BIRTH_YEAR) FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.customer;




// Setting up an additional user
CREATE ROLE DATA_SCIENTIST;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE DATA_SCIENTIST;

CREATE USER DS1 PASSWORD = 'DS1' LOGIN_NAME = 'DS1' DEFAULT_ROLE='DATA_SCIENTIST' DEFAULT_WAREHOUSE = 'DS_WH'  MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE DATA_SCIENTIST TO USER DS1;