USE DATABASE MY_PRACTICE_DB;
CREATE OR REPLACE TABLE CUSTOMERS(ID INT,NAME STRING,CITY STRING);

CREATE OR REPLACE STREAM CUSTOMERS_STREAM ON TABLE CUSTOMERS;

INSERT INTO CUSTOMERS VALUES(2,'RAM','FLORDA'),(3,'RIYA','FLORDA');

SELECT * FROM CUSTOMERS_STREAM;

UPDATE  CUSTOMERS SET CITY ='lAS VEGAS' WHERE ID =3

DELETE FROM CUSTOMERS WHERE ID=1;

UPDATE CUSTOMERS SET CITY='nEW JERSY' WHERE ID=1;